version: '3.1'

services:
  ghost:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ghost_extended
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:2368" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=password
      - database__connection__database=ghost
      - url=http://localhost:2368/
    ports:
      - "2368:2368"
    volumes:
      - ghost_data:/var/lib/ghost/content
    networks:
      - default

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_USER=root
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  ghost_data:
  db_data:

networks:
  default:
    
